version: 1.0.{build}
skip_branch_with_pr: true
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: 'src\QcloudSharp.csproj'
  version: '{version}'
  package_version: '{version}'
install:
  - nuget restore
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
configuration: Release
build:
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
artifacts:
- path: bin\Release\QcloudSharp.dll
  name: QcloudSharp
deploy:
- provider: NuGet
  api_key:
    secure: 7sixps51LfcM9cv9+MuwotnND91/5pdnywrJpZ588wrEmPbxvICFUwAOaUqcnYkM
  on:
    appveyor_repo_tag: true
- provider: GitHub
  description: AppVeyor CI deployment
  auth_token:
    secure: 49h1/SXggw6sDLDix121vnZO1XeUqNJkKUDEwx+QdHQJzEJwO2bgRqOs6HPNDExh
  artifact: QcloudSharp
  draft: false
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true