version: 0.9.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
build:
  publish_nuget: true
  verbosity: detailed
artifacts:
- path: bin\Release\QcloudSharp.dll
  name: QcloudSharp
deploy:
- provider: NuGet
  api_key:
    secure: 7sixps51LfcM9cv9+MuwotnND91/5pdnywrJpZ588wrEmPbxvICFUwAOaUqcnYkM
  on:
    appveyor_repo_tag: true
- provider: GitHub
  description: AppVeyor CI deployment
  auth_token:
    secure: 49h1/SXggw6sDLDix121vnZO1XeUqNJkKUDEwx+QdHQJzEJwO2bgRqOs6HPNDExh
  artifact: QcloudSharp
  draft: true
  prerelease: true
  force_update: true
  on:
    appveyor_repo_tag: true